defmodule Foglet.Accounts.Invite do
  @moduledoc """
  Persisted invite code lifecycle state.

  Public codes are generated by the Accounts context and stored raw so
  registration can redeem them exactly once in later Phase 3 plans.
  """

  use Foglet.Schema

  alias Foglet.Accounts.User

  @type t :: %__MODULE__{}

  @code_format ~r/\A[A-Z0-9]+\z/

  schema "invite_codes" do
    field :code, :string
    field :consumed_at, :utc_datetime_usec
    field :revoked_at, :utc_datetime_usec

    belongs_to :issuer, User
    belongs_to :consumed_by_user, User

    timestamps(type: :utc_datetime_usec)
  end

  @spec changeset(t(), map()) :: Ecto.Changeset.t()
  def changeset(invite, attrs) do
    invite
    |> cast(attrs, [:code])
    |> validate_required([:code])
    |> validate_length(:code, min: 16, max: 64)
    |> validate_format(:code, @code_format, message: "must contain only uppercase letters and digits")
    |> unique_constraint(:code)
  end

  @spec status(t()) :: :available | :consumed | :revoked
  def status(%__MODULE__{revoked_at: %DateTime{}}), do: :revoked
  def status(%__MODULE__{consumed_at: %DateTime{}}), do: :consumed
  def status(%__MODULE__{}), do: :available
end
